baseurl = "http://wiesenpension-cottbus.de/"
title = "Wiesenpension"
theme = "prologue"
languageCode = "de-de"
defaultContentLanguage = "de"
enableRobotsTXT = true
disableRSS = true

[params]
  title = "Dimension"
  description = '<!--[-->A fully responsive site template designed by <a href="https://html5up.net">HTML5 UP</a> and released<!--]--><br />
                <!--[-->for free under the <a href="https://html5up.net/license">Creative Commons</a> license.<!--]-->'
  logo = "fa-bed"
  copyright = "Annette Fiedler"

[blackfriday]
  hrefTargetBlank = true

[languages]

[languages.de]
languageName = "Deutsch"
weight = 2
title = "Wiesenpension"
description = ''
